server:
  port: 8001
spring:
  application:
    name: microservice-sample-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true